name: test

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '*.*'
  pull_request:

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Run tests
        run: sbt "; test; frontend/fullLinkJS"
      - uses: actions/upload-artifact@v2
        with:
          path: 'frontend/.webjar/target/scala-*/classes/META-INF/resources/webjars/pushy-reloaded/*/*'
